---
- name: purge Exim installation
  apt: name={{item}} state=absent purge=yes
  with_items:
  - exim4
  - exim4-base
  - exim4-config
  - exim4-daemon-light
  when: ansible_os_family == "Debian"

- name: Copy over docker-compose.yml
  template:
    src: files/docker-compose.yml
    dest: /home/{{ deploy_user_name }}/docker-compose.yml
  notify:
  - restart stack

- name: Is nginx running?
  shell: "(docker ps | grep nginx) || true"
  register: tmp
  changed_when: false
- set_fact:
    nginx_is_running: "{{ tmp.stdout_lines|length() > 0 }}"

- name: New systemd unit to run docker-compose
  template:
    src: files/mailserver/mailserver.service
    dest: /etc/systemd/system/mailserver.service

- name: Enable mailserver.service
  systemd: name=mailserver.service enabled=true

- name: postfix config directory
  file:
    path: /mnt/docker/mail/postfix
    state: directory
    recurse: yes

- name: postfix config override
  copy:
    src: files/mailserver/custom.conf
    dest: /mnt/docker/mail/postfix/custom.conf
  notify:
  - restart mailserver

- name: nginx sites directory
  file:
    path: /mnt/docker/nginx/sites-enabled
    state: directory
    recurse: yes
    owner: 991
    group: 991

- name: Enable sites
  template:
    src: files/nginx/{{ item }}.conf
    dest: /mnt/docker/nginx/sites-enabled/{{ item }}.conf
    owner: 991
    group: 991
  with_items:
  - postfixadmin
  - rainloop
  notify:
  - restart nginx

- name: Web files here?
  local_action: shell ls www/{{ domain_name }} 2>/dev/null || true
  register: www_dir
  changed_when: false
- set_fact:
    website_setup: "{{ www_dir.stdout_lines|length() > 0 }}"

- name: Set up www site as Contact form.
  template:
    src: files/nginx/www-contact.conf
    dest: /mnt/docker/nginx/sites-enabled/www.conf
    owner: 991
    group: 991
  notify:
  - restart nginx
  when: not website_setup

# For the contact form POST action
- set_fact:
    contact_form_postfix: ""

- name: Set up www site with files.
  block:
  # now create dirs under /mnt/docker/www
  - file:
      path: /mnt/docker/www/{{ item.path }}
      state: directory
      recurse: yes
      owner: 991
      group: 991
    with_filetree: www/{{ domain_name}}
    when: item.state == 'directory'

  # list of non-pdf files
  - local_action:
      module: shell find . -type f | grep -v '\.pdf$'
      args:
        chdir: www/{{ domain_name }}
    register: web_text_files
    changed_when: false
  - local_action:
      module: shell find . -type f -name '*.pdf'
      args:
        chdir: www/{{ domain_name }}
    register: web_pdf_files
    changed_when: false

  # now create files with template
  - template:
      src: www/{{ domain_name }}/{{ item }}
      dest: /mnt/docker/www/{{ item }}
      owner: 991
      group: 991
    with_items: "{{ web_text_files.stdout_lines }}"

  # Copy the pdf files
  - copy:
      src: www/{{ domain_name }}/{{ item }}
      dest: /mnt/docker/www/{{ item }}
      owner: 991
      group: 991
    with_items: "{{ web_pdf_files.stdout_lines }}"

  # Now for the website nginx config
  - template:
      src: files/nginx/www-files.conf
      dest: /mnt/docker/nginx/sites-enabled/www.conf
      owner: 991
      group: 991
    notify:
    - restart nginx
  # In this configuration, the contact POST action needs to go to /contact.
  - set_fact:
      contact_form_postfix: "contact"
  when: website_setup

- name: contact form config directory
  file:
    path: /mnt/docker/contact/{{ item }}
    state: directory
    recurse: yes
    owner: 991
    group: 991
  with_items:
  - config
  - ssmtp

- name: contact config files
  template:
    src: files/contact/{{ item }}
    dest: /mnt/docker/contact/{{ item }}
    owner: 991
    group: 991
  with_items:
  - config/config.php
  - ssmtp/ssmtp.conf
  - index.php
  notify:
  - restart contact
  - restart nginx

- name: rainloop plugin directory
  file:
    path: /mnt/docker/rainloop/_data_/_default_/plugins
    state: directory
    recurse: yes
    owner: 991
    group: 991

- name: copy postfixadmin password change plugin into rainloop
  copy:
    src: files/rainloop/postfixadmin-change-password
    dest: /mnt/docker/rainloop/_data_/_default_/plugins
    owner: 991
    group: 991

# Runs as root, not the deploy user this time.
- name: Start stack if needed
  shell: /usr/local/bin/docker-compose up -d
  args:
    chdir: ~{{ deploy_user_name }}
  when: not nginx_is_running
