---
- name: purge Exim installation
  apt: name={{item}} state=absent purge=yes
  with_items:
  - exim4
  - exim4-base
  - exim4-config
  - exim4-daemon-light
  when: ansible_os_family == "Debian"

- name: Copy over docker-compose.yml
  template:
    src: files/docker-compose.yml
    dest: /home/{{ deploy_user_name }}/docker-compose.yml
  notify:
  - restart stack

- name: Is nginx running?
  shell: "(docker ps | grep nginx) || true"
  register: tmp
  changed_when: false
- set_fact:
    nginx_is_running: "{{ tmp.stdout_lines|length() > 0 }}"

- name: New systemd unit to run docker-compose
  template:
    src: files/mailserver/mailserver.service
    dest: /etc/systemd/system/mailserver.service

- name: Enable mailserver.service
  systemd: name=mailserver.service enabled=true

- name: postfix config directory
  file:
    path: /mnt/docker/mail/postfix
    state: directory
    recurse: yes

- name: nginx directories
  file:
    path: /mnt/docker/{{ item }}
    state: directory
    recurse: yes
    owner: 991
    group: 991
  with_items:
  - nginx/sites-enabled
  - nginx/conf
  - nginx/log

- name: See if nginx access log exists
  stat: path=/mnt/docker/nginx/log/access.log
  register: access_log
  changed_when: false

- name: dummy log file for fail2ban startup
  file:
    path: /mnt/docker/nginx/log/access.log
    state: touch
    owner: 991
    group: 991
  when: not access_log.stat.exists

- name: Set up robots global file (serves /robots.txt)
  copy:
    src: files/nginx/robots
    dest: /mnt/docker/nginx/conf/robots
    owner: 991
    group: 991
  notify:
  - restart nginx

- name: Enable sites
  template:
    src: files/nginx/{{ item }}.conf
    dest: /mnt/docker/nginx/sites-enabled/{{ item }}.conf
    owner: 991
    group: 991
  with_items:
  - postfixadmin
  - rainloop
  - rspamd
  notify:
  - restart nginx

- name: Web files here?
  local_action: shell ls www/{{ domain_name }} 2>/dev/null || true
  register: www_dir
  changed_when: false
  tags:
    - always
- set_fact:
    website_setup: "{{ www_dir.stdout_lines|length() > 0 }}"
  tags:
    - always

- name: Set up www site as Contact form.
  template:
    src: files/nginx/www-contact.conf
    dest: /mnt/docker/nginx/sites-enabled/www.conf
    owner: 991
    group: 991
  notify:
  - restart nginx
  when: not website_setup

# For the contact form POST action
- set_fact:
    contact_form_postfix: ""

- name: Set up www site with files.
  block:
  # now create dirs under /mnt/docker/www
  - file:
      path: /mnt/docker/www/{{ item.path }}
      state: directory
      recurse: yes
      owner: 991
      group: 991
    with_filetree: www/{{ domain_name}}
    when: item.state == 'directory'

  # list of text files
  - local_action:
      module: |
        shell find . -type f | xargs file -i |
        egrep 'text/plain|text/html' | awk -F: '{print $1}'
      args:
        chdir: www/{{ domain_name }}
    register: web_text_files
    changed_when: false
  # list of binary files
  - local_action:
      module: |
        shell find . -type f | xargs file -i |
        egrep -v 'text/plain|text/html' | awk -F: '{print $1}'
      args:
        chdir: www/{{ domain_name }}
    register: web_binary_files
    changed_when: false

  # now create files with template
  - name: Update web site text files
    template:
      src: www/{{ domain_name }}/{{ item }}
      dest: /mnt/docker/www/{{ item }}
      owner: 991
      group: 991
    with_items: "{{ web_text_files.stdout_lines }}"

  # Copy the binary files
  - name: Update web site binary files
    copy:
      src: www/{{ domain_name }}/{{ item }}
      dest: /mnt/docker/www/{{ item }}
      owner: 991
      group: 991
    with_items: "{{ web_binary_files.stdout_lines }}"

  # Now for the website nginx config
  - name: Set up the nginx config
    template:
      src: files/nginx/www-files.conf
      dest: /mnt/docker/nginx/sites-enabled/www.conf
      owner: 991
      group: 991
    notify:
    - restart nginx
  # In this configuration, the contact POST action needs to go to /contact.
  - set_fact:
      contact_form_postfix: "contact"
  when: website_setup
  tags:
    - website

- name: contact form config directory
  file:
    path: /mnt/docker/contact/{{ item }}
    state: directory
    recurse: yes
    owner: 991
    group: 991
  with_items:
  - config
  - ssmtp

- name: contact config files
  template:
    src: files/contact/{{ item }}
    dest: /mnt/docker/contact/{{ item }}
    owner: 991
    group: 991
  with_items:
  - config/config.php
  - ssmtp/ssmtp.conf
  - index.php
  notify:
  - restart contact
  - restart nginx

- name: rainloop plugin directory
  file:
    path: /mnt/docker/rainloop/_data_/_default_/plugins
    state: directory
    recurse: yes
    owner: 991
    group: 991

- name: copy postfixadmin password change plugin into rainloop
  copy:
    src: files/rainloop/postfixadmin-change-password
    dest: /mnt/docker/rainloop/_data_/_default_/plugins
    owner: 991
    group: 991

- name: Install the ufw-docker-hack script
  copy:
    src: files/fail2ban/ufw-docker-hack
    dest: /usr/local/bin/ufw-docker-hack
    mode: 0755

- name: Install ufw-with-docker action for fail2ban
  copy:
    src: files/fail2ban/ufw-with-docker.conf
    dest: /etc/fail2ban/action.d/ufw-with-docker.conf
  notify: Restart fail2ban

- name: fail2ban filter for bots that hit the php apps (301)
  copy:
    src: files/fail2ban/bots-redirect.conf
    dest: /etc/fail2ban/filter.d/bots-redirect.conf
  notify: Restart fail2ban

- name: fail2ban setup for apache_badbots and bots-redirect
  copy:
    src: files/fail2ban/docker-badbots.conf
    dest: /etc/fail2ban/jail.d/docker-badbots.conf
  notify: Restart fail2ban

# Runs as root, not the deploy user this time.
- name: Start stack if needed
  shell: /usr/local/bin/docker-compose up -d
  args:
    chdir: ~{{ deploy_user_name }}
  when: not nginx_is_running
