---
- name: purge Exim installation
  apt: name={{item}} state=absent purge=yes
  with_items:
  - exim4
  - exim4-base
  - exim4-config
  - exim4-daemon-light

- name: Copy over docker-compose.yml
  template:
    src: files/docker-compose.yml
    dest: /home/{{ server_deploy_user_name }}/docker-compose.yml
