---
- name: Is firewalld installed?
  shell: rpm -q firewalld > /dev/null || echo 'Not found'
  register: tmp
  changed_when: false
- set_fact:
    firewalld_installed: "{{ tmp.stdout_lines|length() == 0 }}"

- service: name=firewalld enabled=no state=stopped
  when: firewalld_installed

- name: Install required packages
  dnf: state=latest name={{ item }}
  with_items: "{{ required_packages }}"

- name: Install optional packages
  dnf: state=latest name={{ item }}
  with_items: "{{ optional_packages }}"

- name: Update all packages
  dnf: state=latest name='*'

- name: Set up fail2ban sshd jail
  copy:
    src: files/sshd.conf
    dest: /etc/fail2ban/jail.d/sshd.conf

- service: name=fail2ban enabled=yes state=started
