---
- name: Restart ssh
  service: name={{ ssh_service_name }} state=restarted
- name: Restart cron
  service: name={{ cron_service_name }} state=restarted
- name: Restart fail2ban
  service: name=fail2ban state=restarted
