---
- name: Restart ssh
  service: name={{ ssh_service_name }} state=restarted
- name: Restart cron
  service: name={{ cron_service_name }} state=restarted
- name: Restart ufw
  service: name=ufw state=restarted
