version: '2.1'

services:
  mailserver:
    image: hardware/mailserver:1.1-latest
    container_name: mailserver
    domainname: {{ domain_name }}                  # Mail server A/MX/FQDN & reverse PTR = mail.{{ domain_name }}.
    hostname: mail
    # restart: always
    # extra_hosts:                          - Required for external database (on other server or for local databases on host without docker)
    #  - "mariadb:xx.xx.xx.xx"              - Replace with IP address of MariaDB server
    #  - "redis:xx.xx.xx.xx"                - Replace with IP address of Redis server
    ports:
      - "25:25"       # SMTP                - Required
    # - "110:110"     # POP3       STARTTLS - Optional - For webmails/desktop clients
      - "143:143"     # IMAP       STARTTLS - Optional - For webmails/desktop clients
    # - "465:465"     # SMTPS      SSL/TLS  - Optional - Enabled for compatibility reason, otherwise disabled
      - "587:587"     # Submission STARTTLS - Optional - For webmails/desktop clients
      - "993:993"     # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
    # - "995:995"     # POP3S      SSL/TLS  - Optional - For webmails/desktop clients
      - "4190:4190"   # SIEVE      STARTTLS - Optional - Recommended for mail filtering
    environment:
      - DBPASS={{ user_password }}                      # MariaDB database password (required)
      - RSPAMD_PASSWORD={{ rspamd_password }}             # Rspamd WebUI password (required)
    # - ADD_DOMAINS=aa.tld, www.bb.tld...   # Add additional domains separated by commas (needed for dkim keys etc.)
    # - ENABLE_POP3=true                    # Enable POP3 protocol
    # - ENABLE_FETCHMAIL=true               # Enable fetchmail forwarding
    # - DISABLE_CLAMAV=true                 # Disable virus scanning
    # - DISABLE_SIGNING=true                # Disable DKIM/ARC signing
    # - DISABLE_GREYLISTING=true            # Disable greylisting policy
    # - DISABLE_RATELIMITING=true           # Disable ratelimiting policy
      - RELAY_NETWORKS=172.16.0.0/12        # Includes the docker-compose default network
{% if pgp_encrypt_emails %}
      - ENABLE_ENCRYPTION=true              # See https://github.com/hardware/mailserver#enable-automatic-gpg-encryption
{% endif %}
    #
    # Full list : https://github.com/hardware/mailserver#environment-variables
    #
    volumes:
      - /mnt/docker/mail:/var/mail
{% if not self_signed_certs %}
      - /mnt/docker/nginx/certs:/etc/letsencrypt
{% endif %}
    depends_on:
      - mariadb
      - redis

  # Administration interface
  # https://github.com/hardware/postfixadmin
  # http://postfixadmin.sourceforge.net/
  # Configuration : https://github.com/hardware/mailserver/wiki/Postfixadmin-initial-configuration
  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    domainname: {{ domain_name }}
    hostname: mail
    # restart: always
    environment:
      - DBPASS={{ user_password }}
    depends_on:
      - mailserver
      - mariadb

  # Webmail (Optional)
  # https://github.com/hardware/rainloop
  # https://www.rainloop.net/
  # Configuration : https://github.com/hardware/mailserver/wiki/Rainloop-initial-configuration
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    # restart: always
    volumes:
      - /mnt/docker/rainloop:/rainloop/data
    depends_on:
      - mailserver
      - mariadb

  # Contact Form (Optional)
  # https://github.com/ksylvan/Simple-PHP-Contact-Form
  contact:
    image: kayvan/contact-form
    container_name: contact
    # restart: always
    volumes:
      - /mnt/docker/contact/config:/contact/config
      - /mnt/docker/contact/ssmtp:/etc/ssmtp
      - /mnt/docker/contact/index.php:/contact/index.php
    depends_on:
      - mailserver

  # Web server
  # https://github.com/Wonderfall/dockerfiles/tree/master/nginx
  # https://nginx.org/
  # Configuration : https://github.com/hardware/mailserver/wiki/Reverse-proxy-configuration
  nginx:
    image: wonderfall/boring-nginx
    container_name: nginx
    # restart: always
    ports:
      - "80:8000"
      - "443:4430"
    volumes:
      - /mnt/docker/nginx/sites-enabled:/sites-enabled
      - /mnt/docker/nginx/conf:/conf.d
      - /mnt/docker/nginx/log:/var/log/nginx
{%if self_signed_certs %}
      - /mnt/docker/mail/ssl/selfsigned:/certs
{%else %}
      - /mnt/docker/nginx/certs:/certs
{%endif %}
      - /mnt/docker/www:/www
    depends_on:
      - mailserver
      - postfixadmin
      - rainloop
      - contact

  # Database
  # https://github.com/docker-library/mariadb
  # https://mariadb.org/
  mariadb:
    image: mariadb:10.1
    container_name: mariadb
    # restart: always
    # Info : These variables are ignored when the volume already exists (databases created before).
    environment:
      - MYSQL_ROOT_PASSWORD={{ db_password }}
      - MYSQL_DATABASE=postfix
      - MYSQL_USER=postfix
      - MYSQL_PASSWORD={{ user_password }}
    volumes:
      - /mnt/docker/mysql/db:/var/lib/mysql

  # Cache Database
  # https://github.com/docker-library/redis
  # https://redis.io/
  redis:
    image: redis:3.2-alpine
    container_name: redis
    # restart: always
    command: redis-server --appendonly yes
    sysctls:
      - net.core.somaxconn=1024
    volumes:
      - /mnt/docker/redis/db:/data
